version: 2

models:
  - name: stg_energy__actual # Replace with your actual SQL file name
    description: "Cleaned energy consumption data converted to Berlin time."
    columns:
      - name: '"Datum von"' # Because of the space, we wrap it in single and double quotes
        description: "Start of the recording interval in Berlin time."
        tests:
          - not_null    # CONSTRAINT: This must never be empty
          - unique      # CONSTRAINT: Every row must be a different time (Primary Key)
      - name: '"Datum bis"' # Because of the space, we wrap it in single and double quotes
        description: "End of the recording interval in Berlin time."
        tests:
          - not_null    
          - unique      
